import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Legal | Vero",
  description: "Vero Terms & Conditions and Privacy Policy.",
};

export default function LegalPage() {
  return (
    <main className="min-h-screen bg-white">
      {/* Hero */}
      <section className="bg-[#1e3a5f] text-white">
        <div className="mx-auto max-w-5xl px-6 py-16 text-center sm:py-20">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
            Legal
          </h1>
          <p className="mt-4 text-blue-100">
            Terms &amp; Conditions and Privacy Policy for the Vero platform.
          </p>
          <div className="mt-6 flex justify-center gap-4">
            <a
              href="#terms"
              className="rounded-full bg-white/10 px-5 py-2 text-sm font-medium text-white transition-colors hover:bg-white/20"
            >
              Terms &amp; Conditions
            </a>
            <a
              href="#privacy"
              className="rounded-full bg-white/10 px-5 py-2 text-sm font-medium text-white transition-colors hover:bg-white/20"
            >
              Privacy Policy
            </a>
          </div>
        </div>
      </section>

      <div className="mx-auto max-w-4xl px-6 py-16">
        {/* ===== TERMS & CONDITIONS ===== */}
        <article id="terms" className="scroll-mt-24">
          <h2 className="text-3xl font-bold tracking-tight text-[#1e3a5f]">
            Terms &amp; Conditions
          </h2>
          <p className="mt-2 text-sm text-gray-500">
            Last updated: March 2026
          </p>

          <div className="mt-10 space-y-10 text-gray-700 leading-7">
            {/* 1 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                1. Service Description
              </h3>
              <p className="mt-2">
                Vero (&quot;the Service&quot;) is an AI-based content
                verification platform operated by Vero Lab (&quot;we&quot;,
                &quot;us&quot;, or &quot;our&quot;). The Service allows users to
                submit content&mdash;including images, videos, text, and
                URLs&mdash;via WhatsApp for automated analysis. Vero uses
                artificial intelligence models, forensic analysis tools, and
                multi-source verification to assess content authenticity and
                return a trust score along with a detailed report.
              </p>
            </section>

            {/* 2 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                2. Acceptance of Terms
              </h3>
              <p className="mt-2">
                By sending content to Vero via WhatsApp or using any part of the
                Service, you agree to be bound by these Terms &amp; Conditions.
                If you do not agree to these terms, please do not use the
                Service.
              </p>
            </section>

            {/* 3 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                3. User Responsibilities
              </h3>
              <ul className="mt-2 list-inside list-disc space-y-2">
                <li>
                  You must not use the Service for any unlawful purpose or in
                  violation of any applicable laws or regulations.
                </li>
                <li>
                  You must not attempt to abuse, overload, or interfere with the
                  operation of the Service.
                </li>
                <li>
                  Rate limits apply. Excessive or automated requests may result
                  in temporary or permanent suspension of access.
                </li>
                <li>
                  You are solely responsible for the content you submit to the
                  Service for analysis.
                </li>
                <li>
                  You must not use the Service to harass, defame, or infringe on
                  the rights of any third party.
                </li>
              </ul>
            </section>

            {/* 4 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                4. Disclaimer &amp; Limitations of Analysis
              </h3>
              <p className="mt-2">
                The analysis provided by Vero is advisory in nature and should
                not be treated as definitive or conclusive. Trust scores are
                estimates generated by AI models and forensic tools; they are not
                guarantees of content authenticity or inauthenticity.
              </p>
              <p className="mt-2">
                Vero does not claim to detect all forms of manipulation or
                misinformation. AI models can produce false positives and false
                negatives. Users should exercise their own judgment and, where
                necessary, seek additional verification from authoritative
                sources.
              </p>
            </section>

            {/* 5 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                5. Data Usage
              </h3>
              <p className="mt-2">
                Content you submit to Vero is processed solely for the purpose
                of providing analysis results. We may send your content to
                third-party AI and analysis services as described in our Privacy
                Policy. We do not sell your content or personal data to third
                parties. For full details on data handling, please refer to our{" "}
                <a href="#privacy" className="text-[#0d9488] underline">
                  Privacy Policy
                </a>{" "}
                below.
              </p>
            </section>

            {/* 6 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                6. Intellectual Property
              </h3>
              <p className="mt-2">
                All intellectual property rights in the Service, including but
                not limited to software, algorithms, designs, trademarks, and
                content created by Vero, are owned by Vero Lab or its licensors.
                You may not copy, modify, distribute, or create derivative works
                based on the Service without our prior written consent.
              </p>
              <p className="mt-2">
                You retain ownership of the content you submit for analysis.
                By submitting content, you grant us a limited, non-exclusive
                license to process that content solely for the purpose of
                providing the Service.
              </p>
            </section>

            {/* 7 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                7. Limitation of Liability
              </h3>
              <p className="mt-2">
                To the fullest extent permitted by applicable law, Vero Lab
                shall not be liable for any indirect, incidental, special,
                consequential, or punitive damages, including but not limited to
                loss of profits, data, reputation, or goodwill, arising out of
                or in connection with your use of the Service.
              </p>
              <p className="mt-2">
                Vero Lab&apos;s total liability to you for any claims arising
                from the use of the Service shall not exceed the amount you
                paid, if any, for the Service during the twelve (12) months
                preceding the claim.
              </p>
            </section>

            {/* 8 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                8. Changes to Terms
              </h3>
              <p className="mt-2">
                We reserve the right to update or modify these Terms &amp;
                Conditions at any time. Changes will be effective upon posting
                to this page with a revised &quot;Last updated&quot; date.
                Continued use of the Service after changes are posted
                constitutes acceptance of the revised terms.
              </p>
            </section>

            {/* 9 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                9. Governing Law
              </h3>
              <p className="mt-2">
                These Terms shall be governed by and construed in accordance
                with the laws of the State of Israel, without regard to conflict
                of law principles.
              </p>
            </section>

            {/* 10 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                10. Contact Information
              </h3>
              <p className="mt-2">
                If you have questions about these Terms &amp; Conditions, please
                contact us at{" "}
                <a
                  href="mailto:info@vero-lab.com"
                  className="text-[#0d9488] underline"
                >
                  info@vero-lab.com
                </a>
                .
              </p>
            </section>
          </div>
        </article>

        {/* Divider */}
        <hr className="my-20 border-gray-200" />

        {/* ===== PRIVACY POLICY ===== */}
        <article id="privacy" className="scroll-mt-24">
          <h2 className="text-3xl font-bold tracking-tight text-[#1e3a5f]">
            Privacy Policy
          </h2>
          <p className="mt-2 text-sm text-gray-500">
            Last updated: March 2026
          </p>

          <div className="mt-10 space-y-10 text-gray-700 leading-7">
            {/* 1 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                1. Introduction
              </h3>
              <p className="mt-2">
                Vero Lab (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;)
                respects your privacy and is committed to protecting the
                personal data you share with us. This Privacy Policy explains
                what data we collect, how we use it, and your rights regarding
                that data when you use the Vero content verification service
                (&quot;the Service&quot;).
              </p>
            </section>

            {/* 2 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                2. Data We Collect
              </h3>
              <p className="mt-2">
                When you use the Service, we may collect and process the
                following data:
              </p>
              <ul className="mt-2 list-inside list-disc space-y-2">
                <li>
                  <strong>Phone number:</strong> Your WhatsApp phone number,
                  used to receive your messages and deliver analysis results.
                </li>
                <li>
                  <strong>Content submitted for analysis:</strong> Images,
                  videos, text, and URLs that you send to Vero for
                  verification.
                </li>
                <li>
                  <strong>Analysis results:</strong> Trust scores, detailed
                  reports, and metadata generated during the analysis process.
                </li>
                <li>
                  <strong>Feedback:</strong> Any feedback or follow-up messages
                  you provide regarding analysis results.
                </li>
                <li>
                  <strong>Usage data:</strong> Timestamps, message types, and
                  interaction patterns used to monitor service health and
                  performance.
                </li>
              </ul>
            </section>

            {/* 3 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                3. How We Use Your Data
              </h3>
              <ul className="mt-2 list-inside list-disc space-y-2">
                <li>
                  <strong>To provide analysis:</strong> Your content is
                  processed by our AI models and third-party analysis services
                  to generate verification results.
                </li>
                <li>
                  <strong>To improve the Service:</strong> We use aggregated and
                  anonymized data to improve our AI models, detection accuracy,
                  and overall service quality.
                </li>
                <li>
                  <strong>To generate statistics:</strong> We compile anonymized,
                  aggregate statistics about content trends, misinformation
                  patterns, and service usage. These statistics never identify
                  individual users.
                </li>
                <li>
                  <strong>To communicate with you:</strong> We may send you
                  service-related messages, including analysis results and
                  important updates about the Service.
                </li>
              </ul>
            </section>

            {/* 4 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                4. Data Retention
              </h3>
              <p className="mt-2">
                Analysis results and submitted content are stored for a maximum
                of <strong>30 days</strong> from the date of submission, after
                which they are automatically deleted from our systems. Anonymized
                aggregate statistics may be retained indefinitely.
              </p>
            </section>

            {/* 5 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                5. Third-Party Services
              </h3>
              <p className="mt-2">
                To provide comprehensive analysis, your content may be sent to
                the following third-party services:
              </p>
              <ul className="mt-2 list-inside list-disc space-y-2">
                <li>
                  <strong>Google Gemini AI:</strong> For AI-powered content
                  analysis, text understanding, and image/video interpretation.
                </li>
                <li>
                  <strong>Sightengine:</strong> For forensic image analysis,
                  including AI-generation detection and manipulation detection.
                </li>
                <li>
                  <strong>XPOZ:</strong> For reverse image search and
                  provenance verification.
                </li>
              </ul>
              <p className="mt-2">
                Each third-party service processes data according to its own
                privacy policy. We select partners that maintain appropriate
                data security and privacy standards.
              </p>
            </section>

            {/* 6 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                6. Data Security
              </h3>
              <p className="mt-2">
                We take data security seriously. All data transmitted between
                your device and our servers is encrypted in transit using
                industry-standard TLS encryption. Stored data is secured using
                access controls and encryption at rest. While we implement
                reasonable security measures, no system is completely immune to
                security threats, and we cannot guarantee absolute security.
              </p>
            </section>

            {/* 7 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                7. Your Rights
              </h3>
              <p className="mt-2">You have the right to:</p>
              <ul className="mt-2 list-inside list-disc space-y-2">
                <li>
                  <strong>Request data deletion:</strong> You may request that
                  we delete all personal data and analysis results associated
                  with your phone number at any time.
                </li>
                <li>
                  <strong>Opt out:</strong> You may stop using the Service at
                  any time by simply not sending further messages to Vero.
                </li>
                <li>
                  <strong>Access your data:</strong> You may request a copy of
                  the personal data we hold about you.
                </li>
                <li>
                  <strong>Rectification:</strong> You may request correction of
                  any inaccurate personal data we hold about you.
                </li>
              </ul>
              <p className="mt-2">
                To exercise any of these rights, please contact us at the
                address provided below.
              </p>
            </section>

            {/* 8 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                8. Children&apos;s Privacy
              </h3>
              <p className="mt-2">
                The Service is not intended for use by children under the age of
                13. We do not knowingly collect personal data from children under
                13. If you believe a child under 13 has provided us with
                personal data, please contact us and we will take steps to
                delete that information.
              </p>
            </section>

            {/* 9 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                9. Changes to This Policy
              </h3>
              <p className="mt-2">
                We may update this Privacy Policy from time to time. Changes
                will be effective upon posting to this page with a revised
                &quot;Last updated&quot; date. We encourage you to review this
                page periodically for any updates.
              </p>
            </section>

            {/* 10 */}
            <section>
              <h3 className="text-lg font-semibold text-gray-900">
                10. Contact for Privacy Concerns
              </h3>
              <p className="mt-2">
                If you have questions, concerns, or requests regarding your
                privacy or this Privacy Policy, please contact us at{" "}
                <a
                  href="mailto:privacy@vero-lab.com"
                  className="text-[#0d9488] underline"
                >
                  privacy@vero-lab.com
                </a>
                .
              </p>
            </section>
          </div>
        </article>
      </div>
    </main>
  );
}
